
name: release/unpublished

on:
  release:
    types:
      - unpublished

jobs:
  released:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event }}
      - run: echo ${{ github.event_name }}
