
name: release/created

on:
  release:
    types:
      - created

jobs:
  released:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event }}
      - run: echo ${{ github.event_name }}
