name: release/prereleased

on:
  release:
    types:
      - prereleased

jobs:
  released:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event }}
      - run: echo ${{ github.event_name }}
