
name: release/deleted

on:
  release:
    types:
      - deleted

jobs:
  released:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event }}
      - run: echo ${{ github.event_name }}
