
name: release/edited

on:
  release:
    types:
      - edited

jobs:
  released:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event }}
      - run: echo ${{ github.event_name }}
