name: Show GitHub event

on:
  workflow_call:

jobs:
  show-github-event:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat << OBJECT
          ${{ toJson(github.event) }}
          OBJECT
      - run: |
          cat << OBJECT
          ${{ toJson(github.event_name) }}
          OBJECT
